image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000
- port: 1313
  onOpen: open-preview

tasks:
  - command: 'cd speaker && hugo server --baseUrl $(gp url 1313) --appendPort=false'
