name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      
jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hugo-deploy-gh-pages
      uses: khanhicetea/gh-actions-hugo-deploy-gh-pages@master
      env:
        GITHUB_REMOTE_REPOSITORY: "ross-larson-blog/ross-larson-blog.github.io"
        GITHUB_BRANCH: master
        GIT_DEPLOY_KEY: ${{ secrets.HUGO_DEPLOY }}
        HUGO_VERSION: "0.85.0"
